# Archivo: .github/actions/build-push-microservice/action.yml
name: 'Build and Push Microservice'
description: 'Builds and pushes Docker image for microservices'
inputs:
  service-name:
    description: 'Name of the microservice'
    required: true
  docker-registry:
    description: 'Docker registry username'
    required: true
    default: 'lusalvi'
  dockerfile-path:
    description: 'Path to Dockerfile'
    required: false
    default: './Dockerfile'
  context-path:
    description: 'Build context path'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Check out the repo
      uses: actions/checkout@v4
      shell: bash

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      shell: bash

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      shell: bash

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context-path }}
        file: ${{ inputs.dockerfile-path }}
        push: true
        tags: |
          ${{ inputs.docker-registry }}/${{ inputs.service-name }}:latest
          ${{ inputs.docker-registry }}/${{ inputs.service-name }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
      shell: bash

    - name: Image digest
      run: echo "Image pushed successfully for ${{ inputs.service-name }}"
      shell: bash