# Archivo: ./build-and-push.yml (Frontend)
name: Build and Push Docker Image - Frontend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build and Push Frontend
        uses: ./build-push-microservice
        with:
          service-name: 'frontend'
          docker-registry: 'lusalvi'
          context-path: '.'
          dockerfile-path: './Dockerfile'