name: Deploy to Environment - Frontend

on:
  push:
    tags:
      - 'dev-*'
      - 'test-*'
      - 'prod-*'

jobs:
  extract-env:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set_env.outputs.env }}
    steps:
      - name: Extraer entorno del nombre del tag
        id: set_env
        run: |
          ENVIRONMENT=$(echo "${GITHUB_REF_NAME}" | cut -d'-' -f1)
          echo "env=$ENVIRONMENT" >> $GITHUB_OUTPUT

  deploy:
    needs: extract-env
    runs-on: ubuntu-latest
    environment: ${{ needs.extract-env.outputs.environment }}
    steps:
      - name: Clonar código
        uses: actions/checkout@v4

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build y Push imagen de frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            lusalvi/frontend:${{ github.ref_name }}
            lusalvi/frontend:${{ needs.extract-env.outputs.environment }}